language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run export
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: out
  on:
    branch: master